class carData {
  static Map<String, List<String>> carDataset = {};

  static Map<String, List<String>> getCarData() {
    if (carDataset.isEmpty) {
      Map<String, List<String>> mapOfCarMakeAndModel = {
        "Acura": ["MDX"],
        // "Alfa Romeo S.p.A.": [
        //   "Giulietta",
        //   "Alfa Romeo 4C",
        //   "Alfa Romeo MiTo 2 doors hatchback 1.4",
        //   "Alfa Romeo Giulia",
        //   "Stelvio",
        //   "4C",
        //   "Stelvio Quadrifoglio",
        //   "Stelvio Super Q4",
        //   "Stelvio Veloce Q4",
        //   "Giulia Quadrifoglio",
        //   "Giulia Veloce Q4",
        //   "Giulia Super",
        //   "Giulia Veloce",
        //   "Giulia GTA/m",
        //   "Tonale"
        // ],
        // "Aston Martin": [
        //   "Lagonda",
        //   "Rapide S",
        //   "DB11",
        //   "Vanquish Zagato",
        //   "DB11 V12 AMR",
        //   "Vantage",
        //   "DBS",
        //   "Rapide AMR",
        //   "DBX",
        //   "V8 Vantage",
        //   "DB12"
        // ],
        // "Audi": [
        //   "A8L quattro",
        //   "A7",
        //   "A4",
        //   "RS7",
        //   "Q7 quattro",
        //   "RS6 Avant",
        //   "R8 V10 Plus",
        //   "R8 V10",
        //   "TT",
        //   "S8 quattro",
        //   "SQ5 Quattro",
        //   "Q5 quattro",
        //   "A6 quattro",
        //   "A6",
        //   "S6",
        //   "TTS Coupe",
        //   "TT Quattro",
        //   "A5 quattro",
        //   "A5",
        //   "RS Q3",
        //   "S4",
        //   "S3 quattro",
        //   "A3",
        //   "S3",
        //   "R8",
        //   "Q2",
        //   "RS 3",
        //   "S5",
        //   "TT Roadster",
        //   "RS3 Sportback",
        //   "RS5",
        //   "R8 Spyder",
        //   "Q3",
        //   "Q8 Quattro",
        //   "S7 Quattro",
        //   "Q3 Sportback",
        //   "R8 Coupe",
        //   "RS3 Quattro",
        //   "RS Q8 Quattro",
        //   "RSQ3 Sportback",
        //   "A4 Sedan",
        //   "Q3 1.4",
        //   "S6 Quttro",
        //   "RSQ8 Quattro",
        //   "R8 Spyder",
        //   "RS5 Sporback",
        //   "RS7 Sportback",
        //   "RS6Avant",
        //   "Q5 Sportback",
        //   "RS4 Avant",
        //   "S5",
        //   "S4",
        //   "S5 Coupe",
        //   "Q5",
        //   "S3 Sportback",
        //   "SQ5 Sportback",
        //   "RS6 Avant",
        //   "RS3",
        //   "S8",
        //   "SQ8 Quattro",
        //   "SQ7 Quattro",
        //   "RS3",
        //   "A5",
        //   "A7 Sportback",
        //   "S6",
        //   "A6 Avant",
        //   "A8",
        //   "A8L"
        // ],
        // "BAIC": [
        //   "BJ7150C3D1",
        //   "BJ6470U6X1A",
        //   "X65",
        //   "X35",
        //   "A115",
        //   "BJ40",
        //   "BJ40L",
        //   "X7",
        //   "BJ40L",
        //   "X65",
        //   "A115",
        //   "D50",
        //   "X55",
        //   "U5PLUS"
        // ],
        // "BAIC Yinxiang": ["S3"],
        // "baic yinxiang automobile co.": ["kenbo s6", "kenbo h2"],
        // "Beijing Borgward Automotive Co., Ltd.": ["BX7", "BX5"],
        // "Bentley": [
        //   "Mulsanne Speed",
        //   "Continental GT",
        //   "Continental GT V8 S Convertible",
        //   "Continental GT Convertible",
        //   "Bentayga",
        //   "Mulsanne Extended Wheelbase (EWB)",
        //   "Mulsanne",
        //   "Continental GT W12",
        //   "Flying Spur V8",
        //   "Flying Spur W12",
        //   "Continental GT Convertible W12",
        //   "Continental GT V8",
        //   "Continental GT V8 S",
        //   "Continental GT Convertible V8",
        //   "Continental GT Convertible V8 S",
        //   "Flying Spur V8 S",
        //   "Flying Spur W12 S",
        //   "Continental GT Speed",
        //   "Continental GT Convertible Speed",
        //   "Continental Convertible Supersports",
        //   "Continental Supersports",
        //   "Bentayga V8",
        //   "Bentayga W12",
        //   "Continental GT",
        //   "Mulsanne Speed",
        //   "Mulsanne",
        //   "Mulsanne EWB",
        //   "Continental GT Conv.",
        //   "Bentayga V8",
        //   "Bentayga W12",
        //   "Bentayga Speed",
        //   "Flying Spur",
        //   "GT V8",
        //   "GT V8 Convertible",
        //   "Bentayga Speed",
        //   "Flying Spur V8",
        //   "GT Speed Convertible",
        //   "Bentayga EWB V8"
        // ],
        // "BMW": [
        //   "528i A (5A51)",
        //   "640i A (6H11)",
        //   "640i A (6D01)",
        //   "650i A (6H51)",
        //   "Z4 sDrive18i A (LL11)",
        //   "Z4 sDrive20i A (LL31)",
        //   "X4 xDRIVE 35i A (XW51)",
        //   "750Li A (7F01)",
        //   "M2 A (1H91)",
        //   "440i A (4P11)",
        //   "430i A (4D91)",
        //   "430i A (4T51)",
        //   "420i A (4N31)",
        //   "420i A (4T31)",
        //   "M2 (1H91)",
        //   "420i A (4D31)",
        //   "430i A (4N71)",
        //   "440i A (4T91)",
        //   "M4 A (4S91)",
        //   "440i A (4E31)",
        //   "X1 sDrive 18i A (HS11)",
        //   "420i A (4T31)",
        //   "420i A (4N31)",
        //   "430i A (4D91)",
        //   "440i A (4T91)",
        //   "440i A (4E31)",
        //   "M4 A (4S91)",
        //   "430i A (4N71)",
        //   "420i A (4D31)",
        //   "430i A (4T51)",
        //   "440i A (4P11)",
        //   "ALPINA 440i xDrive A (BF32)",
        //   "ALPINA 650i xDrive A GC (B644)",
        //   "ALPINA 750Li xDrive A (BG12)",
        //   "330i A GT (8X71)",
        //   "340i A (8B31)",
        //   "520i A (5A31)",
        //   "Z4 sDrive28i A (LL51)",
        //   "Z4 sDrive35i A (LM71)",
        //   "528i A GT (SZ61)",
        //   "535i A (5B11)",
        //   "535i A GT (5M21)",
        //   "550i A (KN91)",
        //   "Z4 sDrive35is A (LM11)",
        //   "i8 A (2Z21)",
        //   "550i A GT (5M61)",
        //   "640i A (6F11)",
        //   "640i xDrive A (6D21)",
        //   "640i xDrive A (6F31)",
        //   "640i xDrive A (6H31)",
        //   "650i A (6D41)",
        //   "650i A (6F51)",
        //   "650i xDrive A (6D61)",
        //   "650i xDrive A (6F71)",
        //   "650i xDrive A (6H71)",
        //   "730Li A (7E01)",
        //   "740Li A (7E21)",
        //   "740Li A (7E21)",
        //   "750Li A (7F01)",
        //   "750Li xDrive A (7F21)",
        //   "M135i A (1V11)",
        //   "M140i A (1S91)",
        //   "120i A (1S11)",
        //   "120i A (1U71)",
        //   "125i A (1S31)",
        //   "M240i (2G11)",
        //   "M240i A (2G11)",
        //   "M240i A (2L11)",
        //   "M3 (8M91)",
        //   "125i A (1U91)",
        //   "218i Active Tourer A (2A31)",
        //   "220i A (2F31)",
        //   "220i A (2K31)",
        //   "M3 A (8M91)",
        //   "M4 (3R91)",
        //   "M4 (3U91)",
        //   "M4 A (3R91)",
        //   "225i Active Tourer A (2A71)",
        //   "230i A (2F51)",
        //   "230i A (2K51)",
        //   "318i (8E31)",
        //   "M4 A (3U91)",
        //   "M5 A (FV91)",
        //   "M6 A (6E91)",
        //   "M6 A (6G91)",
        //   "318i A (8E31)",
        //   "320i A (8A11)",
        //   "320i A (8X31)",
        //   "330i A (8A71)",
        //   "M6 A (6J91)",
        //   "X1 sDrive18i A (HS11)",
        //   "X1 sDrive20i A (HS71)",
        //   "X1 xDrive25i A (HT11)",
        //   "X6 M A (KW81)",
        //   "X6 xDrive35i A (KU21)",
        //   "X6 xDrive50i A (KU61)",
        //   "X3 xDrive28i A (WX91)",
        //   "X3 xDrive20i A (WX31)",
        //   "X3 xDrive35i A (WX71)",
        //   "X4 M40i A (XW71)",
        //   "X4 xDrive20i A (XW11)",
        //   "X4 xDrive28i A (XW31)",
        //   "X4 XDRIVE35I A (XW51)",
        //   "X5 M A (KT61)",
        //   "X5 xDrive35i A (KR01)",
        //   "X5 xDrive35i A (KR01)",
        //   "X5 xDrive50i A (KR61)",
        //   "X5 xDrive50i A (KR61)",
        //   "M2 A (1H91)",
        //   "M2 (1H91)",
        //   "530i A (JA51)",
        //   "540i A (JB31)",
        //   "540i A (JB31)",
        //   "M760Li xDrive A (7H61)",
        //   "420i A (4S31)",
        //   "430i A (4S71)",
        //   "440i A (4W71)",
        //   "420i A (4V11)",
        //   "430i A (4V31)",
        //   "440i A (4Z51)",
        //   "420i A (4H31)",
        //   "430i A (4H71)",
        //   "440i A (4J51)",
        //   "M3 A (8M91)",
        //   "M4 (4Y91)",
        //   "M4 A (4Y91)",
        //   "X6 xDrive35i A (KU21)",
        //   "X6 xDrive50i A (KU61)",
        //   "X6 M A (KW81)",
        //   "318i (8E31)",
        //   "318i A (8E31)",
        //   "320i A (8A11)",
        //   "330i A (8A71)",
        //   "530i A (JA51)",
        //   "540i A (JB31)",
        //   "540i A (JB31)",
        //   "730Li A (7E01)",
        //   "M550i xDrive A (JB91)",
        //   "M550i xDrive A (JB91)",
        //   "M760Li xDrive A (7H61)",
        //   "520i A (JA11)",
        //   "M2 (1J51)",
        //   "M2 A (1J51)",
        //   "M240i A (2J51)",
        //   "X1 sDrive20i A (JG31)",
        //   "X3 M40i A (TS31)",
        //   "X3 xDrive30i A (TR91)",
        //   "M4 CS A (3S71)",
        //   "630i A (JV21)",
        //   "M5 A (JF01)",
        //   "X1 sDrive20i A (JG31)",
        //   "X2 sDrive20i A (YH31)",
        //   "M3 CS A (8M91)",
        //   "420i A (4S31)",
        //   "420i A (4V11)",
        //   "430i A (4H71)",
        //   "430i A (4S71)",
        //   "430i A (4V31)",
        //   "440i A (4J51)",
        //   "440i A (4W71)",
        //   "440i A (4Z51)",
        //   "M4 (4Y91)",
        //   "M4 A (4Y91)",
        //   "420i A (4H31)",
        //   "i8 A (2Z41)",
        //   "X4 M40i A (UJ51)",
        //   "X4 xD30i A (UJ31)",
        //   "X6 xD35i A (KU21)",
        //   "X6 xD50i A (KU61)",
        //   "i8 A (2Z61)",
        //   "X1 sDrive20i A(JG31)",
        //   "X2 sDrive20i A(YH31)",
        //   "750Li xDrive A(7F21)",
        //   "M240i Edition A 2J51",
        //   "M760Li xDriveA(7H61)",
        //   "X3 M40i A (TS31)",
        //   "X3 xD30i A (TR91)",
        //   "530i A (JR31)",
        //   "630i A GT (JX61)",
        //   "M2 Competition(2U71)",
        //   "M2 Competition A",
        //   "X5 xDrive40i A(CR61)",
        //   "X5 xDrive50i A(JU21)",
        //   "330i A (5R11)",
        //   "Z4 M40i A (HF51)",
        //   "Z4 sDrive20i A(HF11)",
        //   "Z4 sDrive30i A(HF31)",
        //   "M850i xDrive A(BC41)",
        //   "M850i xDrive A(FY41)",
        //   "X7 xDrive40i A(CW21)",
        //   "X7 xDrive50i A(CX41)",
        //   "M2 Competition A",
        //   "730Li A (7T01)",
        //   "740Li A (7T21)",
        //   "M760Li xDriveA(7U61)",
        //   "750Li xDrive A(7U21)",
        //   "745Le A (7W21)",
        //   "X3 xDrive30i A(TR91)",
        //   "X4 xDrive30i A(UJ31)",
        //   "X3 M A (TS01)",
        //   "X4 M A (UJ01)",
        //   "540i A (JS11)",
        //   "X1sDrive20i A (71AA)",
        //   "320i A (5F31)",
        //   "840i A (AE21)",
        //   "840i A (DZ21)",
        //   "840i A (GV21)",
        //   "M850i xDrive A(GV81)",
        //   "M8 A (AE01)",
        //   "M8 A (DZ01)",
        //   "M340i xDrive A(5U91)",
        //   "M5 A (JF01)",
        //   "X3 M40i A (TY91)",
        //   "X3 xDrive30i A(TY51)",
        //   "X4 M40i A (2V51)",
        //   "X4 xDrive30i A(2V11)",
        //   "X5 M50i A (JU41)",
        //   "X6 M50i A (CY81)",
        //   "X6 xDrive40i A(CY61)",
        //   "X7 M50i A (CX61)",
        //   "520i A (JR11)",
        //   "218i A (11AK)",
        //   "M235i xDrive A(11AL)",
        //   "330i A (5R11)",
        //   "M8 A (GV01)",
        //   "Z4 M40i A (HF91)",
        //   "320i A (5F38)",
        //   "330i A (5R18)",
        //   "X5 M A (JU01)",
        //   "X6 M A (CY01)",
        //   "X3 xDrive30i A(TY55)",
        //   "X1 sDrive18i A(31AA)",
        //   "X1 sDrive20i A(71AA)",
        //   "318i A (71DY)",
        //   "M2CompetitionA(2U71)",
        //   "M2 CS A (1J31)",
        //   "430i A (51AP)",
        //   "530i (51BH)",
        //   "420i A (11AP)",
        //   "M5 A (81CH)",
        //   "M340i xDrive A(5U98)",
        //   "520i A (71AG)",
        //   "M2 CS (1J31)",
        //   "120i A (7K51)",
        //   "430i A (21AT)",
        //   "M3 A (31AY)",
        //   "M4 A (31AZ)",
        //   "M440i xDrive A(11AR)",
        //   "M440i xDrive A(61AT)",
        //   "420i A (11AT)",
        //   "540i A 51BJ",
        //   "M5 CS A 71CH",
        //   "X5 M",
        //   "X6 M",
        //   "M3 Competition 41AY",
        //   "M4 Competition 31BA",
        //   "M4 Competition 41AZ",
        //   "430i A (61AV)",
        //   "M440i xDrive A 11AW",
        //   "420i A (11AV)",
        //   "318i A 78DY",
        //   "X4 xDrive30i A 31DT",
        //   "X3 xDrive30i A 51DP",
        //   "X4 M40i A 41DT",
        //   "X3 M A 11EC",
        //   "X4 M A 21EC",
        //   "M240i xDrive A 51CM",
        //   "X3 xDrive30i A 55DP",
        //   "230i A 21CM",
        //   "XM 21CS",
        //   "M850i xDrive A BC41",
        //   "M850i xDrive A FY41",
        //   "630i A 21BP",
        //   "320i A 51FF",
        //   "320i A 58FF",
        //   "330i A 61FF",
        //   "330i A 68FF",
        //   "735i A 11EH",
        //   "740i A 21EH",
        //   "760i xDrive A 31EJ",
        //   "M4 CSL",
        //   "X7 M60i A 31EM",
        //   "X7 xDrive40i A (21EM)",
        //   "X3 M40i A (81DP)",
        //   "X3 M40i A (85DP)",
        //   "Z4 sDrive20i A (HF11)",
        //   "Z4 sDrive30i A (HF31)",
        //   "X1 xDrive20i A (51EE)",
        //   "M2 (11DM)",
        //   "M2 A (11DM)",
        //   "XM",
        //   "XM Label",
        //   "M850i xDrive",
        //   "840i",
        //   "M8",
        //   "420i",
        //   "430i",
        //   "M3 Competition M xDrive",
        //   "M4 Competition M xDrive",
        //   "M440i xDrive",
        //   "M3 CS",
        //   "X1 sDrive20i",
        //   "X5 M Competition",
        //   "X5 M60i xDrive",
        //   "X5 xDrive40i",
        //   "X6 M Competition",
        //   "X6 M60i xDrive",
        //   "X6 xDrive40i M Sport",
        //   "X7 M60i xDrive",
        //   "X7 xDrive40i",
        //   "M340i xDrive",
        //   "X1 xDrive20i",
        //   "Z4 sDrive20i",
        //   "Z4 sDrive30i",
        //   "120i",
        //   "218i",
        //   "320i",
        //   "330i",
        //   "735i",
        //   "740i",
        //   "760i xDrive",
        //   "M235i xDrive",
        //   "X1 M35i xDrive",
        //   "520i",
        //   "X3 M",
        //   "X3 M40i",
        //   "X3 xDrive30i",
        //   "X4 M",
        //   "X4 M40i",
        //   "X4 xDrive30i",
        //   "230i",
        //   "M2",
        //   "M240i xDrive",
        //   "318i"
        // ],
        // "Borgward": ["BX7", "BX5"],
        // "BYD": [
        //   "New F3",
        //   "S7",
        //   "Song Max",
        //   "Song",
        //   "New F3",
        //   "SONG Pro",
        //   "Qin Pro",
        //   "Tang"
        // ],
        // "Cadillac": [
        //   "SRX",
        //   "ATS",
        //   "ATS_V",
        //   "XTS",
        //   "Escalade",
        //   "CTS",
        //   "CTS-V",
        //   "XT5",
        //   "CT6",
        //   "ATS-V",
        //   "CTS-V",
        //   "Escalade ESV",
        //   "XTS",
        //   "Escalade"
        // ],
        // "Changan": [
        //   "CS35",
        //   "CS75",
        //   "EADO",
        //   "Alsvin V7",
        //   "CS95",
        //   "CS75",
        //   "EADO",
        //   "CS35",
        //   "CS95",
        //   "CS35PLUS",
        //   "Alsvin",
        //   "CS85",
        //   "Hunter",
        //   "Hunter",
        //   "Hunter F70",
        //   "EADO PLUS",
        //   "CS75PLUS",
        //   "UNIT",
        //   "UNIK",
        //   "UNIV",
        //   "UNI-V",
        //   "UNI-T",
        //   "UNI-K"
        // ],
        // "Chery": [
        //   "ARRIZO 3",
        //   "ARRIZO 7",
        //   "TIGGO 5",
        //   "ARRIZO 5",
        //   "Tiggo3",
        //   "ARRIZO 3",
        //   "Tiggo3",
        //   "Tiggo7",
        //   "Tiggo7",
        //   "TIGGO 3",
        //   "TIGGO 7",
        //   "ARRIZO 5",
        //   "TIGGO 5",
        //   "TIGGO 2",
        //   "ARRIZO 6",
        //   "TIGGO 8",
        //   "TIGGO 7 PRO",
        //   "TIGGO 2 PRO",
        //   "TIGGO2",
        //   "TIGGO8 PLUS",
        //   "Arrizo 6 Pro",
        //   "TIGGO4",
        //   "TIGGO8 PRO",
        //   "EXEED TXL",
        //   "TIGGO7 Pro",
        //   "TIGGO4 PRO",
        //   "EXEED VX",
        //   "EXEED LX",
        //   "TIGGO8 PRO MAX",
        //   "TIGGO 8 PRO MAX",
        //   "TIGGO 7 PRO MAX",
        //   "OMODA C5",
        //   "Arrizo 8",
        //   "OMODA S5 GT",
        //   "TIGGO 2 PRO MAX",
        //   "EXEED RX"
        // ],
        // "Chevrolet": [
        //   "Cruze",
        //   "Aveo",
        //   "Sonic",
        //   "Malibu",
        //   "Trax",
        //   "Corvette",
        //   "Impala",
        //   "Tahoe",
        //   "Suburban",
        //   "Silverado",
        //   "Captiva",
        //   "Spark",
        //   "Camaro",
        //   "Traverse",
        //   "Corvette",
        //   "Equinox",
        //   "Equinox",
        //   "Traverse Premier",
        //   "Traverse Premier",
        //   "Traverse LT",
        //   "Traverse LS",
        //   "Traverse LS",
        //   "Traverse LT",
        //   "Spark",
        //   "Equinox LT",
        //   "Equinox LS",
        //   "Impala",
        //   "Tahoe",
        //   "Suburban",
        //   "Equinox Premier",
        //   "Camaro",
        //   "Malibu",
        //   "Silverado",
        //   "Blazer",
        //   "Silverado Pick Up",
        //   "Silverado Trail Boss",
        //   "Captiva",
        //   "Groove",
        //   "Captiva"
        // ],
        // "Chrysler": ["Grand Voyager", "300C", "300C", "300C SRT"],
        // "CHTC MOTOR CO., LTD": ["C4E(HKL6480A)", "C5(HKL6540E4)"],
        // "Citroen": [
        //   "C3 AIRCROSS",
        //   "C4",
        //   "C5 AIRCROSS",
        //   "Spacetourer",
        //   "C4 X",
        //   "Jumpy",
        //   "Spacetourer",
        //   "Berlingo"
        // ],
        // "DFSK": ["DFSK C35", "DFSK C31", "DFSK C32", "FENGON GLORY IX5"],
        // "Dodge": [
        //   "CHALLENGER HELLCAT SRT",
        //   "Charger Hellcat SRT",
        //   "Challenger SRT 8",
        //   "Charger SRT",
        //   "Challenger",
        //   "Charger",
        //   "CHALLENGER HELLCAT SRT",
        //   "Durango"
        // ],
        // "Dong Feng": [
        //   "AX7",
        //   "A30",
        //   "AX7",
        //   "A30",
        //   "AX4",
        //   "T5 EVO",
        //   "A60 MAX",
        //   "U-TOUR",
        //   "T5 EVO HEV",
        //   "SHINE",
        //   "SHINE MAX",
        //   "T5 HEV",
        //   "FORTHING U-TOUR",
        //   "FORTHING T5 EVO"
        // ],
        // "DORCEN": ["G70S"],
        // "EXEED": ["TXL", "EXEED TXL"],
        // "FAW": [
        //   "BESTURN B70",
        //   "BESTURN B30",
        //   "BESTURN X80",
        //   "BESTURN X80",
        //   "Besturn B50",
        //   "BESTURN B70",
        //   "BESTURN X40",
        //   "Besturn  X40",
        //   "Besture B50",
        //   "Besturn X40",
        //   "BESTUNE T77",
        //   "BESTUNE T33",
        //   "HONGQI HS5",
        //   "HONGQI HS7",
        //   "HONGQI H5",
        //   "BESTUNE T77",
        //   "BESTUNE B70",
        //   "BESTUNE T99",
        //   "HONGQI H9",
        //   "HONGQI H7",
        //   "BESTUNE B70S",
        //   "HONGQI H5 OUSADO"
        // ],
        // "FCA Italy S.p.A.": [
        //   "500",
        //   "500C",
        //   "Fiat Tipo Sedan",
        //   "Dodge Neon Sedan",
        //   "Fiorino",
        //   "Fiat 500C Sport",
        //   "Fiat 500 Sport",
        //   "Fiat 500X Street",
        //   "Fiat 500X Trekking",
        //   "Fiat 500X Trekking",
        //   "Fiat Ducato 35 CH1",
        //   "Fiat Ducato 35 MH2",
        //   "Fiat Ducato 35 LH2",
        //   "Fiat Ducato 35 XLH3 MAXI",
        //   "Ram 1200 GL Single cab 2 places",
        //   "Ram 1200 GL Single cab 3 places",
        //   "Ram 1200 GL Double cab 5 places",
        //   "Ram 1200 GL Double cab 6 places",
        //   "Ram 1200 GLX Double cab 5 places",
        //   "Fiat Fullback GL Double cab 6 places",
        //   "Fiat Fullback GLX Double cab 5 places",
        //   "Fiat Fullback GL Single cab 2 places",
        //   "Fiat Fullback GL Single cab 3 places",
        //   "Fiat Fullback GL Double cab 5 places",
        //   "Jeep Renegade TS",
        //   "Jeep Renegade TS Trailhawk",
        //   "Fiat 500C",
        //   "Fiat 500C Sport",
        //   "Fiat 500 Sport",
        //   "Fiat 500",
        //   "Fiat 500X Street",
        //   "Dodge Neon SE",
        //   "Dodge Neon SXT",
        //   "Dodge Neon SXT Plus",
        //   "Fiat Ducato 35 CH1",
        //   "Fiat Ducato 35 MH2",
        //   "Fiat Ducato 35 XLH3 MAXI",
        //   "Fiat 500 Abarth",
        //   "Fiat 500C Abarth",
        //   "Abarth 124 Spider",
        //   "Jeep Renegade TS Sport FWD",
        //   "Jeep Renegade TS Longitude FWD",
        //   "Jeep Renegade TS Trailhawk 4WD",
        //   "Jeep Renegade TS Longitude 4WD",
        //   "Jeep Renegade TS Limited 4WD",
        //   "Ram 1200 GL Double cab",
        //   "Ram 1200 GL Single cab",
        //   "Ram 1200 GLX Double cab",
        //   "Ram 1200 GLS Double cab",
        //   "Ram 1200 GL Double cab",
        //   "Ram 1200 GL Single cab",
        //   "Ram 1200 GLX Double cab",
        //   "Fiat Fiorino",
        //   "Fiat 500X Lounge",
        //   "Fiat 500X Pop Star",
        //   "Jeep Renegade Longit",
        //   "Jeep Renegade Limite",
        //   "Jeep Renegade Trailh",
        //   "ABARTH 595",
        //   "ABARTH 595C",
        //   "Fiat Ducato 35 XLH3",
        //   "Ram 1200 GL",
        //   "Ram 1200 GLX",
        //   "Ram 1200 GLS",
        //   "Fiat 500X City Cross",
        //   "Fiat 500X Cross",
        //   "Jeep Renegade Sport",
        //   "FIAT Ducato LH2",
        //   "Dodge Neon SXT",
        //   "Dodge Neon SE",
        //   "Dodge Neon SXT Plus",
        //   "Fiat Tipo SXT",
        //   "Fiat Tipo SXT Plus",
        //   "Fiat Tipo SE",
        //   "FIAT DUCATO 35 XLH3",
        //   "ABARTH 695",
        //   "ABARTH 695C",
        //   "Fiat 500X"
        // ],
        // "FCA US LLC": [
        //   "Chrysler 200",
        //   "Chrysler 200",
        //   "Jeep Grand Cherokee",
        //   "Jeep Grand Cherokee",
        //   "Jeep Grand Cherokee SRT",
        //   "Jeep Cherokee",
        //   "Jeep Cherokee",
        //   "Dodge Durango",
        //   "Dodge Durango",
        //   "Dodge Viper",
        //   "Jeep Compass",
        //   "Jeep Compass",
        //   "Jeep Wrangler Unlimited",
        //   "Jeep Wrangler Unlimited",
        //   "Jeep Wrangler",
        //   "Jeep Wrangler",
        //   "Chrysler 300",
        //   "Chrysler 300",
        //   "RAM 1500",
        //   "Dodge Charger",
        //   "Dodge Challenger",
        //   "Dodge Challenger",
        //   "Dodge Viper",
        //   "RAM 1500",
        //   "Chrysler Pacifica",
        //   "Chrysler Pacifica",
        //   "Jeep Wrangler JK",
        //   "Jeep Wrangler JK",
        //   "Jeep Wrangler JK Unlimited",
        //   "Jeep Wrangler JK Unlimited",
        //   "RAM 1500 Classic",
        //   "Dodge Charger",
        //   "Jeep Wrangler Unlmtd",
        //   "Jeep Wrangler Unltd",
        //   "Jeep Gladiator",
        //   "RAM 1500 Classic",
        //   "Jeep Gladiator",
        //   "Jeep Wrangler Unltd",
        //   "Jeep Grand Cherokee L",
        //   "Jeep Wagoneer"
        // ],
        // "Ferrari": [
        //   "488 Spider",
        //   "488 GTB",
        //   "GTC 4 Lusso T",
        //   "GTC 4 Lusso",
        //   "488 GTB",
        //   "812 Superfast",
        //   "488 Spider",
        //   "GTC 4 Lusso T",
        //   "Portofino",
        //   "488 Spider Turbo",
        //   "488 PISTA SPIDER",
        //   "488 PISTA",
        //   "F8 TRIBUTO",
        //   "Roma",
        //   "F8 Spider",
        //   "812 GTS",
        //   "SF90 Stradale",
        //   "Portofino M",
        //   "812 Competizione"
        // ],
        // "Fiat": ["500C", "Ducato 35 LH2", "Ducato 35 MH2", "Ducato 35 SH1"],
        // "Ford": [
        //   "Taurus",
        //   "Taurus SHO",
        //   "Flex",
        //   "F150",
        //   "Edge",
        //   "Fusion",
        //   "Focus",
        //   "Escape",
        //   "Explorer",
        //   "Expedition",
        //   "Mustang",
        //   "Flex",
        //   "Ranger",
        //   "GT",
        //   "Ecosport",
        //   "Focus ST with S/S",
        //   "Figo",
        //   "Tourneo",
        //   "Transit",
        //   "Everest",
        //   "Mustang",
        //   "Bronco",
        //   "Taurus",
        //   "Territory"
        // ],
        // "Foton": [
        //   "BJ1037V3KD6-PP",
        //   "BJ5039XXY-1",
        //   "Tunland",
        //   "VIEW CS2",
        //   "VIEW C2",
        //   "VIEW C2 Ambulance",
        //   "VIEW C2 Transor",
        //   "VIEW CS2 Supporter",
        //   "VIEW CS2 Transor",
        //   "VIEW C2 Supporter",
        //   "Tunland E",
        //   "Tunland G",
        //   "Gratour T3"
        // ],
        // "GAC Motor": [
        //   "GS4",
        //   "GS3",
        //   "GA8",
        //   "GS8",
        //   "GS7",
        //   "GA3S",
        //   "GS4",
        //   "GM8",
        //   "GA4",
        //   "GS5",
        //   "GA8",
        //   "GS7",
        //   "GM8",
        //   "GM6",
        //   "GN8",
        //   "GN6",
        //   "GA6",
        //   "EMPOW",
        //   "EMKOO",
        //   "M8"
        // ],
        // "Geely": [
        //   "EX7",
        //   "GC7",
        //   "EMGRAND GT",
        //   "EMGRAND GT",
        //   "EMGRAND X7 SPORT",
        //   "EMGRAND X7 SPORT",
        //   "EMGRAND 7",
        //   "EMGRAND 7",
        //   "EMGRAND GS",
        //   "EMGRAND GS",
        //   "EMGRAND X7",
        //   "EMGRAND X7",
        //   "EMGRAND GL",
        //   "EMGRAND GL",
        //   "The London Taxi Company TX4",
        //   "GC6",
        //   "EMGRAND GT",
        //   "EMGRAND7",
        //   "COOLRAY",
        //   "BINRAY",
        //   "AZKARRA",
        //   "TUGELLA",
        //   "OKAVANGO",
        //   "Emgrand",
        //   "MONJARO",
        //   "LYNK&CO 01",
        //   "LYNK&CO 05",
        //   "LYNK&CO 03",
        //   "LYNK&CO 09",
        //   "LYNK&CO 03+",
        //   "STARRAY"
        // ],
        // "Genesis": [
        //   "G80",
        //   "Genesis G70",
        //   "G90",
        //   "GV80",
        //   "GV70",
        //   "G70 Shooting Brake",
        //   "G70"
        // ],
        // "GMC": [
        //   "Yukon XL",
        //   "Yukon",
        //   "Terrain",
        //   "Sierra",
        //   "Acadia",
        //   "Yukon Denali",
        //   "Yukon XL Denali",
        //   "Terrain Denali",
        //   "Yukon Denali",
        //   "Yukon XL Denali",
        //   "Acadia",
        //   "Terrain SLE",
        //   "Terrain SLT",
        //   "Yukon",
        //   "Yukon XL",
        //   "Sierra",
        //   "Sierra AT4",
        //   "Sierra Pick Up",
        //   "Terrain",
        //   "Canyon"
        // ],
        // "Great Wall": [
        //   "H9",
        //   "Wingle 6",
        //   "H8",
        //   "H2",
        //   "Wingle 6",
        //   "Wingle 5",
        //   "HAVAL H9",
        //   "HAVAL H9",
        //   "HAVAL H2",
        //   "HAVAL H6",
        //   "Wingle 5",
        //   "wingle 7",
        //   "Wingle 5",
        //   "HAVAL H9",
        //   "HAVAL H2",
        //   "HAVAL H6",
        //   "Wingle 7",
        //   "Great Wall POER",
        //   "HAVAL JOLION",
        //   "POER",
        //   "HAVAL DARGO",
        //   "HAVAL H6S",
        //   "HAVAL H6GT",
        //   "TANK 300",
        //   "KINGKONG POER",
        //   "TANK 500"
        // ],
        // "Hawtai": ["A25"],
        // "Honda": [
        //   "Odyssey",
        //   "Accord",
        //   "ACCORD 2.4 LX",
        //   "ACCORD 24LXi",
        //   "ACCORD 2.4 LX (Sunroof)",
        //   "ACOORD 2.4 LX (Sunroof)",
        //   "ACCORD 2.4 EX",
        //   "ACCORD 24EXi",
        //   "ACCORD 2.4 EX (Leather)",
        //   "ACCORD 24SPORT",
        //   "ACCORD 3.5 EX",
        //   "ACCORD 35EXi",
        //   "ACCORD 3.5 SPORT",
        //   "ACCORD 35SPORT",
        //   "ODYSSEY J EX",
        //   "ODYSSEY J EXV",
        //   "CIVIC LXI",
        //   "CIVIC EXI",
        //   "CIVIC RS",
        //   "HONDA CITY EX 1.5L Sedan 4x2 4Doors",
        //   "CITY",
        //   "ACCORD COUPE 2.4 EX",
        //   "ACCORD 2.4 DX",
        //   "ACCORD 2.4 EXL",
        //   "ACCORD COUPE V6 EXG",
        //   "ODYSSEY J EXV",
        //   "PILOT EX 4WD",
        //   "PILOT EXL",
        //   "PILOT TOURING",
        //   "PILOT EX 2WD",
        //   "CIVIC DX",
        //   "CIVIC LXI",
        //   "CR-V Touring 4WD",
        //   "CR-V DX 2WD",
        //   "CR-V EX",
        //   "CR-V LX 2WD",
        //   "City LX",
        //   "City EX",
        //   "Odyssey LX",
        //   "Odyssey EXL",
        //   "Odyssey Touring",
        //   "CIVIC LXISP",
        //   "CIVIC EXI",
        //   "CIVIC RS",
        //   "CR-V LX",
        //   "CR-V TOURING",
        //   "CR-V DX",
        //   "PILOT EX",
        //   "ACCORD 1.5 Turbo EX",
        //   "ACCORD EXLAEB",
        //   "ACCORD 20SPRT",
        //   "ACCORD 1.5 Turbo LX",
        //   "ACCORD SPORT",
        //   "City DX",
        //   "City LX",
        //   "City EX",
        //   "PILOT LX",
        //   "HR-V LX",
        //   "HR-V EX",
        //   "HR-V DX",
        //   "ACCORD EX",
        //   "ACCORD LX",
        //   "Pilot SE",
        //   "CITY LX SPORT",
        //   "Odyssey-J EXV",
        //   "Odyssey-J EX",
        //   "ACCORD EXL",
        //   "ACCORD LX SPORT",
        //   "City Sport",
        //   "Civic LX",
        //   "Civic SPORT",
        //   "HR-V LX",
        //   "HR-V EX",
        //   "CIVIC TYPE R",
        //   "ZR-V EX",
        //   "ZR-V LX",
        //   "Pilot Sport",
        //   "Pilot TRG",
        //   "Accord e: EXL",
        //   "Accord e: Sport"
        // ],
        // "Huanghai": ["HHN2N", "HHN2Q", "HHN1VJ"],
        // "Hyundai": [
        //   "H1",
        //   "Genesis",
        //   "Creta",
        //   "Creta",
        //   "Azera",
        //   "Tucson",
        //   "Elantra",
        //   "Accent",
        //   "Sonata",
        //   "Santa Fe",
        //   "Grand i10",
        //   "I30",
        //   "Veloster",
        //   "I40",
        //   "Grand Santa Fe",
        //   "Genesis G90",
        //   "G90L",
        //   "Genesis G80",
        //   "Genesis G80",
        //   "Santafe",
        //   "Grand Santafe",
        //   "IONIQ",
        //   "IONIQ",
        //   "Genesis G90",
        //   "Genesis G70",
        //   "Genesis G70",
        //   "Sonata Hybrid",
        //   "Sonata Hybrid",
        //   "Veloster",
        //   "H1",
        //   "Grand i10",
        //   "Azera",
        //   "Grand Santafe",
        //   "Sonata",
        //   "Accent",
        //   "Tucson",
        //   "Kona",
        //   "Santafe",
        //   "Elantra",
        //   "PALISADE",
        //   "Veloster N",
        //   "Venue",
        //   "Genesis GV80",
        //   "Genesis GV70",
        //   "STARIA",
        //   "Kona Hybrid",
        //   "Elantra N",
        //   "Elantra HEV",
        //   "Tucson HEV",
        //   "Creta Grand",
        //   "Santa Fe",
        //   "Santafe HEV",
        //   "Elantra CN7 HEV"
        // ],
        // "INEOS": ["GRENADIER SW"],
        // "Infiniti": [
        //   "QX50",
        //   "QX60",
        //   "QX80",
        //   "Q30",
        //   "Q30",
        //   "Q50",
        //   "QX70",
        //   "Q70",
        //   "Q60",
        //   "Q30S",
        //   "QX30",
        //   "QX30",
        //   "Q30S",
        //   "QX80",
        //   "QX50",
        //   "Q50",
        //   "Q60",
        //   "QX60",
        //   "Q70",
        //   "QX70",
        //   "QX55"
        // ],
        // "Isuzu": ["D-MAX", "mu-X", "D-MAX", "mu-X"],
        // "JAC": ["S5", "S3", "T8", "S3", "JS4", "S7 Pro", "M4", "J7", "JS6"],
        // "Jaguar": [
        //   "F-Type S",
        //   "F-Type",
        //   "F-Type R",
        //   "XE",
        //   "XJ",
        //   "XJ",
        //   "XF",
        //   "XE S",
        //   "XF S",
        //   "F-Type Manual Transmission",
        //   "F-Type R",
        //   "F-Type S",
        //   "F-Type SVR",
        //   "F-Type S British Design Edition",
        //   "F-Type",
        //   "F-PACE Prestige",
        //   "F-PACE Portfolio",
        //   "F-PACE S",
        //   "F-PACE First Edition",
        //   "F-PACE R-Sport",
        //   "F-PACE Pure",
        //   "XE Prestige (High)",
        //   "XE R-Sport (High)",
        //   "XE Portfolio (High)",
        //   "XE Pure (High)",
        //   "XE Pure (Low)",
        //   "XE Prestige (Low)",
        //   "XE R-Sport (Low)",
        //   "XE Portfolio (Low)",
        //   "XF Pure",
        //   "XF Prestige",
        //   "XF Portfolio",
        //   "XF R-Sport",
        //   "XF Pure",
        //   "XF Prestige",
        //   "XF R-Sport",
        //   "XF Portfolio",
        //   "F-Type S British Design Edition",
        //   "XJ LWB LUXURY",
        //   "XJ LWB PREMIUM LUXURY",
        //   "XJ SWB XJR",
        //   "XJ LWB LUXURY",
        //   "XJ LWB PREMIUM LUXURY",
        //   "XJ LWB PORTFOLIO",
        //   "XJ LWB R-SPORT",
        //   "XJ LWB AUTOBIOGRAPHY",
        //   "XJ LWB PORTFOLIO",
        //   "XJ LWB AUTOBIOGRAPHY",
        //   "XJ LWB XJR",
        //   "XJ SWB LUXURY",
        //   "XJ SWB LUXURY",
        //   "XJ SWB R-SPORT",
        //   "F-PACE Pure",
        //   "​F-TYPE 280KW Auto R-Dynamic",
        //   "F-TYPE 294KW Auto 400 Sport",
        //   "F-TYPE 294KW Auto 400 Sport",
        //   "F-TYPE 423KW Auto SVR",
        //   "F-PACE Prestige",
        //   "​F-TYPE 250KW Auto",
        //   "​F-TYPE 280KW Auto",
        //   "F-TYPE 405KW Auto R",
        //   "F-TYPE 405KW Auto R",
        //   "​F-TYPE 250KW Manual R-Dynamic",
        //   "​F-TYPE 280KW Auto R-Dynamic",
        //   "F-TYPE 280KW Manual",
        //   "​F-TYPE 250KW Auto",
        //   "F-PACE R-Sport",
        //   "XF S",
        //   "​F-TYPE 250KW Manual R-Dynamic",
        //   "​F-TYPE 280KW Auto",
        //   "F-PACE Portfolio",
        //   "F-PACE S",
        //   "​F-TYPE 250KW Auto R-Dynamic",
        //   "​F-TYPE 250KW Manual",
        //   "​F-TYPE 250KW Auto R-Dynamic",
        //   "​F-TYPE 250KW Manual",
        //   "F-TYPE 280KW Manual R-Dynamic",
        //   "F-TYPE 280KW Manual",
        //   "XE Portfolio (Low)",
        //   "XE S",
        //   "XE Prestige (Mid)",
        //   "XE R-Sport (Mid)",
        //   "XE Portfolio (Mid)",
        //   "XE R-Sport (Low)",
        //   "XE Pure (Mid)",
        //   "XE Pure (Low)",
        //   "XE Prestige (Low)",
        //   "XF Prestige 5Doors",
        //   "XF R-Sport 5Doors",
        //   "F-TYPE 221KW Auto 2Doors",
        //   "F-TYPE 221KW Auto R-Dynamic 2Doors",
        //   "F-TYPE 221KW Auto 2Doors",
        //   "F-TYPE 221KW Auto R-Dynamic 2Doors",
        //   "XE Prestige (High)",
        //   "XE R-Sport (High)",
        //   "XE Portfolio (High)",
        //   "E-PACE Standard",
        //   "E-PACE R-Dynamic Base",
        //   "E-PACE S",
        //   "E-PACE HSE",
        //   "E-PACE First Edition",
        //   "E-PACE R-Dynamic S",
        //   "E-PACE R-Dynamic SE",
        //   "E-PACE SE",
        //   "E-PACE R-Dynamic HSE",
        //   "F-PACE Pure (High)",
        //   "F-PACE Prestige (High)",
        //   "F-PACE Portfolio (High)",
        //   "F-PACE R-Sport (High)",
        //   "XJ LWB XJR575",
        //   "XJ SWB XJR575",
        //   "XJ LWB R-SPORT",
        //   "XJ SWB R-SPORT",
        //   "XF R-Sport (High)",
        //   "XF Prestige (High)",
        //   "XF Portfolio (High)",
        //   "XF S 5Doors",
        //   "XF First Edition 5Doors",
        //   "XJR575 LWB",
        //   "XJR575 SWB",
        //   "E-Pace 147kW",
        //   "​F-TYPE 250kW",
        //   "F-TYPE 221kW",
        //   "​F-TYPE 280KW",
        //   "F-TYPE 280kW",
        //   "F-TYPE 423kW",
        //   "F-TYPE 250kW",
        //   "F-TYPE 405kW",
        //   "XJ 346kW",
        //   "XJ 250kW",
        //   "XJ 423kW",
        //   "XJ 375kW",
        //   "XE 280kW",
        //   "XE 221kW",
        //   "XE 147kW",
        //   "F-Pace 221kW",
        //   "XE 184kW",
        //   "F-Pace 184kW",
        //   "F-Pace 280kW",
        //   "XF 280kW",
        //   "XF 184kW",
        //   "XF 221kW",
        //   "E-PACE 183kW",
        //   "XE Project 8",
        //   "F-Pace SVR",
        //   "F-TYPE 221kW",
        //   "F-PACE 294kW",
        //   "E Pace I4P",
        //   "F -TYPE 221kW",
        //   "F TYPE 331KW",
        //   "F -TYPE 423kW",
        //   "F PACE 294kW",
        //   "F TYPE 423KW",
        //   "F TYPE 221KW",
        //   "F-TYPE 331KW"
        // ],
        // "Jeep": [
        //   "WRANGLER",
        //   "WRANGLER UNLIMITED",
        //   "Grand Cherokee",
        //   "Grand Cherokee SRT"
        // ],
        // "Jetour": [
        //   "X70",
        //   "X70S",
        //   "X70S",
        //   "X90",
        //   "X95",
        //   "X70PLUS",
        //   "X90PLUS",
        //   "Dashing"
        // ],
        // "Jiangling Motors Co., Group": ["QILING"],
        // "JMC": ["Boarding", "Vigus", "Vigus Plus"],
        // "KAIYI AUTOMOBILE": ["X3", "X3 Pro", "E5"],
        // "KG Mobility Corp": [
        //   "Ssangyong Torres",
        //   "Ssangyong Korando",
        //   "Ssangyong Tivoli",
        //   "Ssnagyong Tivoli"
        // ],
        // "Kia": [
        //   "Sorento",
        //   "Carnival",
        //   "Cerato",
        //   "Picanto",
        //   "Rio",
        //   "Carens",
        //   "Sportage",
        //   "Soul",
        //   "Cadenza",
        //   "Sportage",
        //   "Mohave",
        //   "Quoris",
        //   "Optima",
        //   "Optima Turbo",
        //   "Grand Carnival",
        //   "CK Stinger",
        //   "UM PE SORENTO",
        //   "UM PE SORENTO",
        //   "UM PE SORENTO",
        //   "UM PE SORENTO",
        //   "UM PE SORENTO",
        //   "UM PE SORENTO",
        //   "UM PE SORENTO",
        //   "UM PE SORENTO",
        //   "UM PE SORENTO",
        //   "UM PE SORENTO",
        //   "CK Stinger",
        //   "CADENZA",
        //   "MOHAVE",
        //   "PICANTO",
        //   "CARENS",
        //   "SORENTO",
        //   "RIO",
        //   "SOUL",
        //   "NIRO",
        //   "STINGER",
        //   "OPTIMA",
        //   "GRAND CARNIVAL",
        //   "Cerato",
        //   "K900",
        //   "Telluride",
        //   "Pegas",
        //   "Seltos",
        //   "KIA PICANTO",
        //   "KIA RIO SC",
        //   "KIA RIO",
        //   "SK3 SOUL",
        //   "KIA CADENZA",
        //   "KIA YG CADENZA",
        //   "KIA K900",
        //   "RJ K5",
        //   "DL3 K5",
        //   "KIA DL3 K5",
        //   "KIA ON TELLURIDE",
        //   "KIA CERATO",
        //   "KIA STINGER",
        //   "KIA SPORTAGE",
        //   "KIA SELTOS",
        //   "KIA SP2i SELTOS",
        //   "MQ4 SORENTO",
        //   "DL3 K5 HEV",
        //   "CARNIVAL",
        //   "SONET",
        //   "SONET",
        //   "RIO 4DR",
        //   "RIO 5DR",
        //   "GL3 K8",
        //   "RIO SC",
        //   "NQ5E SPORTAGE",
        //   "K5 DL3",
        //   "K5 HEV DL3",
        //   "SORENTO MQ4",
        //   "SOUL SK3",
        //   "K8 GL3"
        // ],
        // "Lamborghini": [
        //   "Aventador",
        //   "Aventador SV",
        //   "Aventador Roadster",
        //   "Huracan",
        //   "Aventador SV Roadster",
        //   "Huracan Spyder",
        //   "Huracan Spyder",
        //   "Aventador",
        //   "Aventador SV Roadster",
        //   "Aventador SV",
        //   "Aventador Roadster",
        //   "Aventador S",
        //   "Centenario Roadster",
        //   "Huracan Performante",
        //   "Aventador S",
        //   "Aventador S Roadster",
        //   "Huracan Performante Spyder",
        //   "AVENT ADOR S",
        //   "URUS V8 T",
        //   "HURACAN COUPE",
        //   "Huracan",
        //   "HURACAN P S",
        //   "Huracan Performante",
        //   "HURACAN P COUPE",
        //   "Aventador SVJ",
        //   "URUS V 8 T",
        //   "Huracan EVO Spyder",
        //   "Huracan EVO",
        //   "Huracan EVO",
        //   "Aventador S Coupè",
        //   "Aventador SVJ Coupè",
        //   "Aventador SVJ",
        //   "Urus V8T",
        //   "Aventador SIAN Roads",
        //   "Aventador SIAN Coupè",
        //   "Huracan STO",
        //   "Aventador Countach",
        //   "Urus Performante",
        //   "Urus S",
        //   "Huracan Tecnica",
        //   "Huracan Sterrato"
        // ],
        // "Land Rover": [
        //   "Range Rover",
        //   "Range Rover Evoque Coupe",
        //   "Range Rover Evoque Coupe SE Plus",
        //   "Range Rover Evoque Coupe HSE Dynamic",
        //   "Range Rover Evoque Coupe Autobiography",
        //   "Range Rover Evoque Coupe HSE",
        //   "Range Rover Evoque 5 Door HSE Dynamic",
        //   "Range Rover Evoque 5 Door Autobiography",
        //   "Range Rover Evoque 5 Door SE Plus",
        //   "Range Rover Evoque 5 Door PURE",
        //   "Range Rover Evoque 5 Door SE",
        //   "Range Rover Evoque 5 Door HSE",
        //   "Discovery Sport PURE 5 Seat",
        //   "Discovery Sport SE 5 Seat",
        //   "Discovery Sport HSE 5 Seat",
        //   "Discovery Sport HSE LUXURY 5 Seat",
        //   "Discovery Sport PURE 7 Seat",
        //   "Discovery Sport SE 7 Seat",
        //   "Discovery Sport HSE 7 Seat",
        //   "Discovery Sport HSE LUXURY 7 Seat",
        //   "Range Rover Evoque 2 Door SE Dynamic",
        //   "Range Rover Evoque 2 Door HSE Dynamic",
        //   "Range Rover Sport V8SC HSE Dynamic 7 Seat",
        //   "Range Rover Sport V6SC AB Dynamic 7 Seat",
        //   "Range Rover Sport V6SC SE 7 Seat",
        //   "Range Rover Sport V8SC AB Dynamic 7 Seat",
        //   "Range Rover Sport V6SC HSE Dynamic 7 Seat",
        //   "Range Rover Sport V8SC SVR 5 Seat",
        //   "Range Rover Sport V8SC HSE Dynamic 5 Seat",
        //   "Range Rover Sport V8SC AB Dynamic 5 Seat",
        //   "Range Rover Sport V6SC AB Dynamic 5 Seat",
        //   "Range Rover Sport V6SC SE 5 Seat",
        //   "Range Rover Sport V6SC HSE Dynamic 5 Seat",
        //   "Range Rover Sport V6SC HSE 5 Seat",
        //   "Range Rover Sport V6SC HSE 7 Seat",
        //   "Range Rover LWB V8SC SVA 4 seat Executive",
        //   "Range Rover LWB V8SC AB 4 seat Executive",
        //   "Range Rover LWB V8SC AB 5 Seat",
        //   "Range Rover LWB V8SC Vogue SE 4 seat Executive Class",
        //   "Range Rover LWB V8SC Vogue SE 5 Seat",
        //   "Range Rover LWB V8SC Vogue 5 Seat",
        //   "Range Rover LWB V6SC 280KW Vogue 5 Seat",
        //   "Range Rover SWB V8SC SVA Dynamic 5 Seat",
        //   "Range Rover SWB V8SC AB 4 seat Executive",
        //   "Range Rover LWB V6SC 250KW Vogue 5 Seat",
        //   "Range Rover SWB V8SC AB 5 Seat",
        //   "Range Rover SWB V8SC Vogue SE 4 seat Executive",
        //   "Range Rover SWB V6SC 280KW Vogue",
        //   "Range Rover SWB V8SC Vogue SE 5 Seat",
        //   "Range Rover SWB V8SC Vogue 5 Seat",
        //   "Range Rover SWB V6SC 250KW Vogue",
        //   "Range Rover SWB V6SC 280KW HSE",
        //   "Range Rover SWB V6SC 250KW HSE",
        //   "Discovery V6SC HSE Luxury 5 Seat",
        //   "Discovery V6SC HSE 5 Seat",
        //   "Discovery V6SC SE 7 Seat",
        //   "Discovery V6SC Pure 7 Seat",
        //   "Discovery V6SC HSE Luxury 7 Seat",
        //   "Discovery V6SC HSE 7 Seat",
        //   "Discovery V6SC First Edition 7 Seat",
        //   "Discovery V6SC SE 5 Seat",
        //   "Discovery V6SC Pure 5 Seat",
        //   "Range Rover Velar 184kw S",
        //   "Range Rover Velar 184kw HSE",
        //   "Range Rover Velar 184kw R-Dynamic S",
        //   "Range Rover Velar 184kw R-Dynamic HSE",
        //   "Range Rover Velar 184kw SE",
        //   "Range Rover Velar 184kw R-Dynamic (Base)",
        //   "Range Rover Velar 184kw R-Dynamic SE",
        //   "Range Rover Velar 280kw Standard",
        //   "Range Rover Velar 184kw Standard",
        //   "Range Rover Velar 280kw First Edition",
        //   "Range Rover Velar 280kw R-Dynamic HSE",
        //   "Range Rover Velar 280kw R-Dynamic SE",
        //   "Range Rover Velar 280kw R-Dynamic S",
        //   "Range Rover Velar 280kw R-Dynamic (Base)",
        //   "Range Rover Velar 280kw HSE",
        //   "Range Rover Velar 280kw SE",
        //   "Range Rover Velar 280kw S",
        //   "Range Rover Evoque 5 Door Autobiography",
        //   "Range Rover Evoque 5 Door SE Plus",
        //   "Range Rover Evoque 2 Door SE Dynamic",
        //   "Range Rover Evoque 2 Door HSE Dynamic",
        //   "Range Rover Evoque Coupe SE Plus",
        //   "Range Rover Evoque 5 Door PURE",
        //   "Range Rover Evoque Coupe HSE",
        //   "Range Rover Evoque Coupe HSE Dynamic",
        //   "Range Rover Evoque Coupe Autobiography",
        //   "Range Rover Evoque 5 Door HSE Dynamic",
        //   "Range Rover Evoque 5 Door HSE",
        //   "Range Rover Evoque 5 Door Dynamic Special Edition",
        //   "Range Rover Evoque 5 Door SE",
        //   "Discovery Sport HSE LUXURY 7 Seat",
        //   "Discovery sport V6SC HSE Luxury 7 Seat",
        //   "Discovery Sport SE 5 Seat",
        //   "Discovery Sport HSE 5 Seat",
        //   "Discovery Sport HSE LUXURY 5 Seat",
        //   "Discovery Sport PURE 7 Seat",
        //   "Discovery Sport SE 7 Seat",
        //   "Discovery sport V6SC SE 7 Seat",
        //   "Discovery Sport HSE 7 Seat",
        //   "Discovery sport V6SC HSE 7 Seat",
        //   "Discovery Sport PURE 5 Seat",
        //   "Range Rover Velar 221kw HSE",
        //   "Range Rover Velar 221kw R-Dynamic HSE",
        //   "Range Rover Velar 221kw R-Dynamic S",
        //   "Range Rover Velar 221kw R-Dynamic (Base)",
        //   "Range Rover Velar 221kw SE",
        //   "Range Rover Velar 221kw R-Dynamic SE",
        //   "Range Rover Velar 221kw S",
        //   "Range Rover Velar 221kw Standard",
        //   "Discovery V6SC HSE 7 Seat",
        //   "Discovery V6SC HSE 5 Seat",
        //   "Discovery I4 S 7 Seat",
        //   "Discovery I4 S 5 Seat",
        //   "Discovery I4 HSE 5 Seat",
        //   "Discovery V6SC Pure 7 Seat",
        //   "Discovery V6SC SE 7 Seat",
        //   "Discovery V6SC Pure 5 Seat",
        //   "Discovery V6SC HSE Luxury 7 Seat",
        //   "Discovery V6SC HSE Luxury 5 Seat",
        //   "Discovery V6SC SE 5 Seat",
        //   "Discovery I4 HSE Luxury 7 Seat",
        //   "Discovery I4 HSE 7 Seat",
        //   "Discovery I4 SE 7 Seat",
        //   "Discovery I4 HSE Luxury 5 Seat",
        //   "Discovery I4 SE 5 Seat",
        //   "Range Rover Sport V6SC HSE 7 SEAT",
        //   "Range Rover Sport I4 HSE 5 Seat",
        //   "Range Rover Sport V8SC HSE Dynamic 7 Seat",
        //   "Range Rover Sport V8SC HSE Dynamic 5 Seat",
        //   "Range Rover Sport V8SC SVR 5 Seat Only",
        //   "Range Rover Sport V6SC Autobiography Dynamic 5 Seat",
        //   "Range Rover Sport V8SC Autobiography Dynamic 7 Seat",
        //   "Range Rover Sport V8SC Autobiography Dynamic 5 Seat",
        //   "Range Rover Sport I4 SE 7 Seat",
        //   "Range Rover Sport I4 HSE 7 Seat",
        //   "Range Rover Sport V6SC Autobiography Dynamic 7 Seat",
        //   "Range Rover Sport V6SC SE 7 Seat",
        //   "Range Rover Sport V6SC HSE Dynamic 7 Seat",
        //   "Range Rover Sport V6SC SE 5 Seat",
        //   "Range Rover Sport V6SC HSE Dynamic 5 Seat",
        //   "Range Rover Sport V6SC HSE 5 Seat",
        //   "Range Rover Sport I4 SE 5 Seat",
        //   "Range Rover LWB V8SC Vogue 5 Seat",
        //   "Range Rover SWB V8SC Autobiography 5 Seat",
        //   "Range Rover SWB V8SC Vogue SE 5 Seat",
        //   "Range Rover SWB V8SC Vogue 5 Seat",
        //   "Range Rover SWB V6SC 280KW Vogue",
        //   "Range Rover SWB V6SC 250KW Vogue",
        //   "Range Rover LWB V8SC Autobiography 5 Seat",
        //   "Range Rover SWB V6SC 280KW HSE",
        //   "Range Rover SWB V6SC 250KW HSE",
        //   "Range Rover Evoque 5 Door Dynamic Special Edition",
        //   "Range Rover",
        //   "Range Rover Velar",
        //   "Range Rover Sport",
        //   "Discovery V6 7 Seat",
        //   "Discovery V6 5 Seat",
        //   "Discovery I4 7 Seat",
        //   "Discovery I4 5 Seat",
        //   "Discovery Sport",
        //   "Range Rover Evoque",
        //   "Range Rover Coupe",
        //   "Defender 110",
        //   "Defender 110",
        //   "Defender 90",
        //   "Discovery 5 Seat",
        //   "Discovery 7 Seat",
        //   "Discovery I6P 5 Seat",
        //   "Discovery I6P 7 Seat",
        //   "Discovery Sport I4P",
        //   "Range Rover I6P",
        //   "Range Rover V8P",
        //   "Discovery",
        //   "Defender 130",
        //   "Defender I4P",
        //   "Defender V8P",
        //   "Defender I6P",
        // ],
        // "LANDWIND": ["X5 PLUS"],
        // "Lexus": [
        //   "ES250",
        //   "ES350",
        //   "LS600h",
        //   "LS460",
        //   "CT200h",
        //   "IS350",
        //   "IS200t",
        //   "RC F",
        //   "GS450h",
        //   "NX200t",
        //   "LX450d",
        //   "LX570",
        //   "GX460",
        //   "RX350",
        //   "RX450h",
        //   "GS200t",
        //   "GS350",
        //   "RC200t",
        //   "RC350",
        //   "GSF",
        //   "RX450h",
        //   "RC200t",
        //   "GS200t",
        //   "GS450h",
        //   "GS F",
        //   "LS600hL",
        //   "LS600hL",
        //   "LX450d",
        //   "LS460L",
        //   "LS460L",
        //   "IS200t",
        //   "LC500",
        //   "LC500h",
        //   "LC500h",
        //   "LC500",
        //   "NX300",
        //   "NX300",
        //   "GS F",
        //   "GS300",
        //   "LS350",
        //   "LS350",
        //   "LS500h",
        //   "LS500h",
        //   "IS300",
        //   "RC300",
        //   "RC350",
        //   "RX350L",
        //   "RX450hL",
        //   "LS500",
        //   "LS500",
        //   "GSF",
        //   "RX350",
        //   "ES250",
        //   "ES350",
        //   "ES300h",
        //   "GX460",
        //   "GS350",
        //   "IS300",
        //   "IS350",
        //   "CT200h",
        //   "LC 500",
        //   "LX570",
        //   "UX200",
        //   "UX200",
        //   "RC F",
        //   "RX 450hL",
        //   "NX350",
        //   "NX350h",
        //   "LX600",
        //   "LX500d",
        //   "RX500h",
        //   "RX350h"
        // ],
        // "LEXUS": [
        //   "GSF",
        //   "RX350",
        //   "ES250",
        //   "ES350",
        //   "ES300h",
        //   "GX460",
        //   "GS350",
        //   "IS300",
        //   "IS350",
        //   "CT200h",
        //   "LC 500",
        //   "LX570",
        //   "UX200",
        //   "UX200",
        //   "RC F",
        //   "RX 450hL",
        //   "NX350",
        //   "NX350h",
        //   "LX600",
        //   "LX500d",
        //   "RX500h",
        //   "RX350h"
        // ],
        // "Lifan": ["LIFAN 820", "LF1022"],
        // "Lincoln": [
        //   "MKS",
        //   "MKT",
        //   "MKZ",
        //   "Navigator",
        //   "Navigator L",
        //   "MKX",
        //   "MKT",
        //   "MKS",
        //   "MKZ Select",
        //   "MKZ Premier",
        //   "Continental Select",
        //   "Continental Reserve",
        //   "Continental Premier",
        //   "Navigator Reserve",
        //   "Navigator Select",
        //   "Navigator L Select",
        //   "Navigator L Reserve",
        //   "MKC Reserve",
        //   "MKC Select",
        //   "MKC Premier",
        //   "MKX Select",
        //   "MKX Premier",
        //   "MKX Reserve",
        //   "MKZ Reserve",
        //   "MKZ Select",
        //   "MKZ Premier",
        //   "Continental Presidential",
        //   "MKZ Presidential",
        //   "MKX Presidential",
        //   "ContinentalPresident",
        //   "Nautilus Select",
        //   "Nautilus Reserve",
        //   "Nautilus Premier",
        //   "Nautilus Presidntial",
        //   "Aviator Presidential",
        //   "Aviator Base",
        //   "Aviator Signature",
        //   "MKZ Base",
        //   "Aviator Reserve",
        //   "Corsair Standard",
        //   "Corsair Reserve",
        //   "Nautilus Standard",
        //   "ContinentalPrsdntial",
        //   "Continental Standard",
        //   "Aviator Standard",
        //   "Nautilus Presidential"
        // ],
        // "Mahindra & Mahindra": ["Scorpio"],
        // "Maserati": [
        //   "Quattroporte GTS",
        //   "Quattroporte",
        //   "Quattroporte S Q4",
        //   "Levante",
        //   "Ghibli",
        //   "Ghibli S",
        //   "Ghibli S Q4",
        //   "Levante S",
        //   "Granturismo Sport",
        //   "Quattroporte GTS",
        //   "Levante",
        //   "Ghibli S",
        //   "Quattroporte S Q4",
        //   "Ghibli S Q4",
        //   "Ghibli",
        //   "Levante S",
        //   "Levante GTS",
        //   "Levante Trofeo",
        //   "GRAN TURISMO SPORT",
        //   "QUATTROPORTE",
        //   "Quattroporte S",
        //   "Quattroporte Trofeo"
        // ],
        // "Mazda": [
        //   "Mazda3",
        //   "Mazda6",
        //   "MX",
        //   "BT-50",
        //   "CX-3",
        //   "CX-9",
        //   "CX-3",
        //   "CX-5",
        //   "MX-5",
        //   "Mazda3",
        //   "Mazda6",
        //   "CX-9",
        //   "MX-5",
        //   "CX-5",
        //   "CX-30",
        //   "BT-50",
        //   "CX-60",
        //   "Mazda2",
        //   "CX-90"
        // ],
        // "McLaren": [
        //   "McLaren 650S Coupe",
        //   "McLaren 650S Spider",
        //   "McLaren 675LT Coupe",
        //   "McLaren 540C Coupe",
        //   "McLaren 570S Coupe",
        //   "McLaren 675LT Spider",
        //   "McLaren 650S Can-Am",
        //   "McLaren 570GT",
        //   "McLaren 540C Coupe",
        //   "McLaren 570S Coupe",
        //   "720S",
        //   "McLaren 570S Spider",
        //   "McLaren 570GT",
        //   "Senna",
        //   "570GT",
        //   "540C Coupe",
        //   "570S Spider",
        //   "720S Coupe",
        //   "570S Coupe",
        //   "600LT Coupe",
        //   "720S Spider",
        //   "600LT Spider",
        //   "540C",
        //   "570S",
        //   "GT",
        //   "McLaren 620R",
        //   "720S Le Mans",
        //   "765LT Coupe",
        //   "McLaren Elva",
        //   "765LT Spider",
        //   "750S Spider",
        //   "750S Coupe"
        // ],
        // "Mercedes-Benz": [
        //   "AMG GLE 63",
        //   "AMG GLE 63 S 4MATIC",
        //   "GLE 500 4MATIC",
        //   "GLS 500 4MATIC",
        //   "C 200",
        //   "C 300",
        //   "S 500 4MATIC",
        //   "S 500",
        //   "GLE 400 4MATIC",
        //   "AMG GLS 63 4MATIC",
        //   "GLE 500 4MATIC",
        //   "Vito 116",
        //   "AMG C 63 S Coupe",
        //   "AMG S 63 4MATIC",
        //   "V-Class V 250",
        //   "SLC 200",
        //   "SL 500",
        //   "AMG SL 63",
        //   "SL 400",
        //   "SLC 300",
        //   "AMG SLC 43",
        //   "AMG A 45 4MATIC",
        //   "AMG GLS 63 4MATIC",
        //   "GLA 250 4MATIC",
        //   "A 250",
        //   "AMG GLE 63 4MATIC",
        //   "CLA 250 4MATIC",
        //   "AMG GLA 45 4MATIC",
        //   "AMG CLA 45 4MATIC",
        //   "GLS 500 4MATIC",
        //   "AMG GT S",
        //   "AMG GT",
        //   "E 200",
        //   "GLE 400 4MATIC",
        //   "GLC 300 4MATIC",
        //   "GLC 250 4MATIC",
        //   "AMG GLE 63 S 4MATIC",
        //   "AMG GLE 43 4MATIC",
        //   "AMG GLC 43 4MATIC",
        //   "E 320",
        //   "CLS 500",
        //   "S 600 Maybach",
        //   "C 63 AMG S",
        //   "AMG S 65",
        //   "S 320",
        //   "C 300",
        //   "AMG S 63 4MATIC",
        //   "CLS 400",
        //   "AMG C 63 S",
        //   "E 250",
        //   "AMG S 65",
        //   "AMG CLS 63",
        //   "AMG CLS 63 S 4MATIC",
        //   "S 400",
        //   "C 250",
        //   "C 400 4MATIC",
        //   "AMG C 63 S",
        //   "S 600",
        //   "AMG C 43 4MATIC",
        //   "C 180",
        //   "E 400",
        //   "AMG C 63",
        //   "V-class V250",
        //   "AMG C 43 4MATIC",
        //   "E 400 4MATIC",
        //   "G 500",
        //   "E 300",
        //   "AMG E 43 4MATIC",
        //   "AMG G 63 4MATIC",
        //   "GLC 250 4MATIC",
        //   "GLC 300 4MATIC",
        //   "AMG GLC 43 4MATIC",
        //   "G 500 4x4 Squared",
        //   "AMG E 63 S 4MATIC",
        //   "E 400 4MATIC",
        //   "E300",
        //   "AMG A 45 4MATIC",
        //   "CLA 250 4MATIC",
        //   "GLA 250 4MATIC",
        //   "AMG GLA 45 4MATIC",
        //   "AMG CLA 45 4MATIC",
        //   "AMg GT R",
        //   "AMG GT C",
        //   "AMG GT C",
        //   "SLC 300",
        //   "S 450",
        //   "S 560 4MATIC",
        //   "SLC 200",
        //   "C 400 4MATIC",
        //   "SL 500",
        //   "AMG GLE 43 4MATIC",
        //   "GLE 500 e 4MATIC",
        //   "AMG G 65",
        //   "AMG GLC 63 S 4MATIC",
        //   "AMG E 63 S 4MATIC",
        //   "AMG E 43 4MATIC",
        //   "S 560",
        //   "S 650 Maybach",
        //   "S 560 4MATIC",
        //   "Sprinter 215",
        //   "Vito",
        //   "A 200",
        //   "Mercedes-Benz A 250",
        //   "S 560",
        //   "Vito Tourer",
        //   "Vito Tourer",
        //   "AMG G 63",
        //   "SL 400",
        //   "E 200",
        //   "E 250",
        //   "S 560 e",
        //   "E 200 Convertible",
        //   "E 300",
        //   "CLA 200",
        //   "GLA 220 4MATIC",
        //   "G 500",
        //   "AMG E 53 4MATIC",
        //   "GLA 200",
        //   "AMG GLC 63 S 4MATIC",
        //   "CLS 53",
        //   "CLS 350",
        //   "AMG E 53 4MATIC",
        //   "AMG GT R",
        //   "AMG GT S Coupe",
        //   "E 450 4MATIC",
        //   "E 350",
        //   "GLC 350 e 4MATIC",
        //   "E 450",
        //   "CLS 450 4MATIC",
        //   "C 180",
        //   "S 320",
        //   "C 200 Coupe",
        //   "C 300 Coupe",
        //   "C 200",
        //   "GLS 400 4MATIC",
        //   "AMG GT 63 S 4MATIC+",
        //   "GLE 450 4MATIC",
        //   "AMG GT 53 4MATIC+",
        //   "A 250 Sedan",
        //   "A 200",
        //   "GLS 450 4MATIC",
        //   "V-Class V250",
        //   "S 320 Sedan",
        //   "S 450 Sedan",
        //   "GLC 200 4MATIC",
        //   "A 35 4MATIC",
        //   "A 250",
        //   "AMG A 35 4MATIC",
        //   "S 560 Maybach",
        //   "S 63 4MATIC",
        //   "AMG GT S",
        //   "AMG 53 4MATIC",
        //   "AMG E 63 S 4MATIC+",
        //   "E 450 4MATIC",
        //   "AMG CLS 53 4MATIC+",
        //   "AMG GLE 53 4MATIC+",
        //   "CLA 250",
        //   "AMG CLA 35 4MATIC",
        //   "AMG A 45 S 4MATIC+",
        //   "GLS 580 4MATIC",
        //   "GLB 250 4MATIC",
        //   "AMG GLB 35 4MATIC",
        //   "AMG GT 43",
        //   "AMG E 53 4MATIC+",
        //   "AMG GT Black Series",
        //   "S 500 4MATIC",
        //   "S 450 4MATIC",
        //   "Vito 116 CDI",
        //   "GLA 35 4MATIC",
        //   "GLA 45",
        //   "CLA 35 4MATIC",
        //   "CLA 45",
        //   "E 53 4MATIC+",
        //   "E300",
        //   "S 580 4MATIC",
        //   "S 580 Maybach",
        //   "GLB 200",
        //   "G 63",
        //   "S 680 Maybach",
        //   "GLE 63 S",
        //   "AMG SL 55 4MATIC",
        //   "AMG A 35 4MATIC"
        // ],
        // "Mini": [
        //   "JOHN COOPER WORKS A CONVERTIBLE (WH91)",
        //   "JOHN COOPER WORKS CONVERTIBLE (WH91)",
        //   "JOHN COOPER WORKS CONVERTIBLE (WH91)",
        //   "JOHN COOPER WORKS A CONVERTIBLE (WH91)",
        //   "Cooper (XM51)",
        //   "Cooper (XS51)",
        //   "Cooper A (WG31)",
        //   "Cooper A (XM51)",
        //   "Cooper A (XS51)",
        //   "Cooper A Clubman (LN31)",
        //   "Cooper S (XM71)",
        //   "Cooper S A (WG71)",
        //   "Cooper S A (XM71)",
        //   "Cooper S A (XM71)",
        //   "Cooper S A (XS71)",
        //   "Cooper S A Clubman (LN71)",
        //   "John Cooper Works (XM91)",
        //   "John Cooper Works A (XM91)",
        //   "John Cooper Works A Clubman (LV91)",
        //   "Cooper A Countryman (YS31)",
        //   "Cooper S ALL4 A Countryman (YT11)",
        //   "John Cooper Works ALL4 A Countryman (YV91)",
        //   "Cooper S A Clubman (LN71)",
        //   "John Cooper Works ALL4 A Clubman (LV91)",
        //   "John Cooper Works ALL4 Clubman (LV91)",
        //   "John Cooper Works (XM91)",
        //   "John Cooper Works A (XM91)",
        //   "John Cooper Works ALL4 A Countryman (YV91)",
        //   "Cooper A Countryman (YS31)",
        //   "Cooper S ALL4 A Countryman (YT11)",
        //   "John Cooper Works (XR91)",
        //   "John Cooper Works A (XR91)",
        //   "Cooper A (WJ31)",
        //   "Cooper A (XR31)",
        //   "Cooper A (XU71)",
        //   "Cooper S A (WJ51)",
        //   "Cooper S A (XR51)",
        //   "Cooper S A (XU91)",
        //   "JC Works (XR91)",
        //   "JC Works A (WJ91)",
        //   "JC Works A (XR91)",
        //   "Cooper S A (LN71)",
        //   "Cooper A (LN31)",
        //   "Cooper A (YS31)",
        //   "Cooper S ALL4 A YT11",
        //   "JC Works ALL4 A LV91",
        //   "JC Works ALL4 A YV91",
        //   "JC Works ALL4 (LV91)",
        //   "Cooper S A (LV71)",
        //   "Cooper S ALL4 A YX11",
        //   "Cooper A (LV31)",
        //   "JCW ALL4 A (YZ91)",
        //   "Cooper A (YW31)",
        //   "JCW ALL4 A (JZ91)",
        //   "JC Works GP A (XX91)",
        //   "Cooper A (21BR)",
        //   "Cooper S ALL4 A(81BR",
        //   "JCW ALL4 A (31BS)",
        //   "JCW ALL4 A 31BS",
        //   "JCW A 61DL",
        //   "John Cooper Works A 71DH",
        //   "Cooper S A 41DL",
        //   "Cooper S A 51DH",
        //   "Cooper S A 51DK",
        //   "Cooper A 31DH",
        //   "Cooper A 31DK",
        //   "One A 21DH",
        //   "One A 21DK",
        //   "Clubman Cooper S",
        //   "Clubman John Cooper Works ALL4",
        //   "Cooper",
        //   "Cooper S",
        //   "Countryman Cooper",
        //   "Countryman Cooper S",
        //   "Countryman John Cooper Works ALL4",
        //   "John Cooper Works",
        // ],
        // "Mitsubishi": [
        //   "Outlander",
        //   "outlander",
        //   "L200",
        //   "Pajero",
        //   "Lancer",
        //   "Montero Sport",
        //   "Montero Sport",
        //   "ASX",
        //   "Attrage",
        //   "SPACE STAR",
        //   "SPACE STAR",
        //   "ECLIPSE CROSS",
        //   "ECLIPSE CROSS",
        //   "ASX",
        //   "ATTRAGE",
        //   "PAJERO",
        //   "L200",
        //   "XPANDER",
        //   "ATTARGE",
        //   "XPANDER CROSS",
        // ],
        // "Nissan": [
        //   "Pathfinder",
        //   "Nissan Pick up",
        //   "Nissan Pick up",
        //   "Patrol_4WD",
        //   "Patrol",
        //   "X-TRAIL 2WD",
        //   "X-TRAIL 4WD",
        //   "X-TRAIL 4WD",
        //   "Sentra",
        //   "NP300",
        //   "Sunny",
        //   "Navara",
        //   "Altima",
        //   "370Z",
        //   "GTR",
        //   "Maxima",
        //   "Kicks",
        //   "Kicks",
        //   "X-TRAIL 2WD",
        //   "Urvan",
        //   "FUSO Canter Van",
        //   "FUSO Canter Van",
        //   "X-trail",
        //   "Sunny",
        //   "370Z",
        //   "Urvan",
        //   "Patrol",
        //   "Navara",
        //   "GT-R",
        //   "X-Trail",
        //   "Altima",
        //   "Maxima",
        //   "Sentra",
        //   "Pathfinder",
        //   "X-TERRA",
        //   "Z",
        // ],
        // "Peugeot": [
        //   "508",
        //   "Partner",
        //   "308",
        //   "3008",
        //   "5008",
        //   "208",
        //   "Boxer",
        //   "301",
        //   "2008",
        //   "Boxer L2H2",
        //   "Expert",
        //   "Traveller",
        //   "Expert",
        //   "Boxer",
        //   "Partner",
        //   "RIFTER",
        //   "LANDTREK",
        //   "408",
        // ],
        // "Porsche": [
        //   "911 Carrera R",
        //   "718 Boxster",
        //   "718 Boxster S",
        //   "718 Boxster S",
        //   "Macan Basic",
        //   "Macan S",
        //   "Macan Turbo",
        //   "Macan GTS",
        //   "911 Carrera",
        //   "911 Carrera 4",
        //   "911 Carrera S",
        //   "911 Carrera 4S",
        //   "911 Targa 4",
        //   "911 Turbo S",
        //   "911 Targa 4S",
        //   "911 Turbo",
        //   "Cayenne Basic",
        //   "Cayenne Turbo",
        //   "Cayenne S",
        //   "Cayenne GTS",
        //   "718 Cayman",
        //   "718 Cayman",
        //   "718 Cayman S",
        //   "718 Cayman S",
        //   "Panamera Turbo",
        //   "Panamera Turbo Executive",
        //   "Panamera 4S Executive",
        //   "Panamera 4S",
        //   "Macan Turbo with performance package",
        //   "911 Carrera 4 GTS",
        //   "911 Carrera GTS",
        //   "911 Targa 4 GTS",
        //   "Panamera 4",
        //   "Panamera Basic",
        //   "Panamera Basic",
        //   "Panamera 4 Executive",
        //   "911 GT3",
        //   "Macan Basic",
        //   "Macan GTS",
        //   "Cayman S",
        //   "Cayman",
        //   "Cayenne Basic",
        //   "Panamera Turbo Executive",
        //   "Panamera 4S Executive",
        //   "Panamera 4 E-hybrid",
        //   "Panamera Turbo S E-hybrid",
        //   "911 turbo S Exclusive Series",
        //   "718 Boxster GTS",
        //   "718 Cayman GTS",
        //   "911 GT2 RS",
        //   "911 GT3 Touring Package",
        //   "Panamera 4S Sport Turismo",
        //   "Panamera Turbo Sport Turismo",
        //   "911 Carrera T",
        //   "911 Carrera T",
        //   "Cayenne Turbo",
        //   "Cayenne S",
        //   "911 GT3 RS",
        //   "911 Carrera 4 GTS",
        //   "911 Carrera S",
        //   "718 Cayman",
        //   "Cayenne E-hybrid",
        //   "Panamera 4 Executive",
        //   "Macan S",
        //   "Panamera GTS",
        //   "Panamera 4S",
        //   "911 Speedster",
        //   "911 Carrera 4 S",
        //   "911 Carrera 4S",
        //   "718 Boxster",
        //   "Panamera GTS",
        //   "Cayenne Coupe",
        //   "Cayenne Turbo Coupe",
        //   "Cayenne S Coupe",
        //   "911 Carrera",
        //   "Macan Turbo",
        //   "718 Cayman GT4",
        //   "718 Spyder",
        //   "718 Boxster GTS",
        //   "911 Turbo",
        //   "911 Turbo S",
        //   "911 Carrera 4",
        //   "911 Carrera 4 S",
        //   "911 Carrera  S",
        //   "911 Carrera  S",
        //   "911 Targa 4S",
        //   "911 Targa 4",
        //   "Cayenne GTS Coupe",
        //   "Panamera 4",
        //   "Panamera Turbo",
        //   "Panamera Turbo S",
        //   "911 Carrera GTS",
        //   "911 Targa 4 GTS",
        //   "Cayenne GTS",
        //   "718 Boxster T",
        //   "718 Cayman T",
        //   "Macan T",
        //   "911 GT3",
        //   "Cayenne Turbo GT",
        //   "718 Cayman GT4 RS",
        //   "911 Sport Classic",
        //   "911 Dakar",
        //   "Cayenne GT Coupe",
        //   "718 Spyder RS",
        //   "911 ST",
        // ],
        // "Qoros": [
        //   "Qoros 5",
        //   "Qoros 7",
        // ],
        // "RAM": [
        //   "RAM 1500",
        // ],
        // "Renault": [
        //   "DUSTER",
        //   "Talisman",
        //   "Dokker",
        //   "Symbol",
        //   "Duster",
        //   "Koleos",
        //   "CAPTUR",
        //   "Symbol Ph 2",
        //   "Megane",
        //   "Megane",
        //   "Talisman",
        //   "Megane GT",
        //   "Master",
        //   "Master",
        //   "Megane",
        //   "Captur",
        //   "Dokker",
        //   "Symbol",
        //   "Koleos",
        //   "Megane RS",
        //   "Master L1 H1",
        //   "Master L2 H2",
        //   "Express",
        //   "Megane RS",
        //   "Megane Trophy",
        //   "Express E",
        //   "Koleoes E",
        //   "Duster E",
        //   "Koleos E",
        //   "Megane E",
        //   "Megane Ultime",
        // ],
        // "Rolls-Royce": [
        //   "Ghost (FK41)",
        //   "Phantom (FJ61)",
        //   "Dawn (XZ81)",
        //   "Phantom",
        //   "Phantom Drophead",
        //   "Ghost A (FK41)",
        //   "Ghost A EWB (XZ41)",
        //   "Wraith A (XZ01)",
        //   "Dawn A (XZ81)",
        //   "Wraith A Black Badge (XZ01)",
        //   "Ghost A Black Badge (FK41)",
        //   "Dawn A (XZ81)",
        //   "Ghost A (FK41)",
        //   "Ghost A EWB (XZ41)",
        //   "Wraith A (XZ01)",
        //   "Ghost A Black Badge (FK41)",
        //   "Wraith A Black Badge (XZ01)",
        //   "Dawn A Black Badge (XZ81)",
        //   "Phantom A (TT61)",
        //   "Phantom A EWB (TT81)",
        //   "Phantom A (TT61)",
        //   "Phantom A EWB (TT81)",
        //   "Dawn A BB (XZ81)",
        //   "Ghost A BB (FK41)",
        //   "Wraith A BB (XZ01)",
        //   "Cullinan A (TV41)",
        //   "Ghost A Black Badge",
        //   "Cullinan A BB (TV81)",
        //   "Ghost A (TV01)",
        //   "Ghost EWB A (TV21)",
        //   "Dawn A (XZ81)",
        //   "Ghost BB A TD61",
        //   "Ghost A TV01",
        //   "Ghost EWB A TV21",
        //   "Phantom EWB A TT81",
        //   "Wraith Black Badge A XZ01",
        //   "Cullinan Black Badge A TV81",
        //   "Dawn Black Badge A XZ81",
        //   "Cullinan",
        //   "Cullinan Black Badge",
        //   "Ghost",
        //   "Ghost Black Badge",
        //   "Ghost EWB",
        //   "Phantom",
        //   "Phantom EWB",
        // ],
        // "SAIC": [
        //   "MG 6",
        //   "MG5",
        //   "MG 350",
        //   "MG 3",
        //   "MG GS",
        //   "MG GS",
        //   "MG GT",
        //   "MG GT",
        //   "MG360",
        //   "MG360",
        //   "MG ZS",
        //   "MG ZS",
        //   "MG RX5",
        //   "MG RX5",
        //   "MG6",
        //   "MG RX8",
        //   "MG5",
        //   "MG T60",
        //   "MG T60",
        //   "MG HS",
        //   "MG 5",
        //   "MG 6",
        //   "MG5 GT",
        //   "MAXUS D90",
        //   "MAXUS D60",
        //   "MAXUS G50",
        //   "MAXUS G10",
        //   "MAXUS T60",
        //   "MAXUS V80",
        //   "D90 Pro",
        //   "MAXUS T70 Pro",
        //   "MG EHS",
        //   "MAXUS T90",
        //   "MAXUS D90 Pro",
        //   "MAXUS G90",
        //   "MG ONE",
        //   "D60 MAX",
        //   "MUSUX D90 MAX",
        //   "MAXUS D90 Max",
        //   "MG Whale",
        //   "T60",
        // ],
        // "Shanxi Victory Automobile Manufacturing Co.,Ltd.": [
        //   "K1",
        //   "V1",
        //   "V2",
        //   "K1",
        //   "V2",
        //   "V1",
        // ],
        // "SINOTRUK": [
        //   "U70 Pro",
        //   "U70Pro",
        //   "U75 Plus",
        // ],
        // "Skoda": [
        //   "Octavia",
        //   "Rapid",
        //   "Superb",
        //   "Fabia",
        //   "Kodiaq",
        //   "Kodiaq",
        //   "Rapid",
        //   "Superb",
        //   "Octavia",
        //   "Fabia",
        //   "Kamiq",
        //   "Scala",
        // ],
        // "SOUEAST": [
        //   "DX7",
        //   "DX5",
        //   "DX3",
        // ],
        // "South East（Fujian）Motor CO.,Ltd": [
        //   "DX3",
        //   "DX7 prime",
        //   "A5",
        //   "DX7",
        //   "DX5",
        // ],
        // "SsangYong": [
        //   "XLV",
        //   "XLV",
        //   "Tivoli",
        //   "Korando",
        //   "Rexton",
        //   "Musso",
        //   "Tivoli",
        //   "Rexton",
        //   "MUSSO GRAND",
        //   "Korando",
        //   "Torres",
        // ],
        // "Subaru": [
        //   "Legacy",
        //   "Outback",
        //   "Forester",
        //   "WRX",
        //   "WRX STI",
        //   "XV",
        //   "BRZ",
        //   "Impreza",
        //   "WRX STI",
        //   "WRX",
        //   "Forester",
        //   "Impreza",
        //   "SUBARU XV",
        //   "Legacy",
        //   "Outback",
        //   "XV",
        //   "SUBARU FORESTER",
        //   "CROSSTREK",
        // ],
        // "Suzuki": [
        //   "Jimny",
        //   "Ertiga",
        //   "CIAZ",
        //   "Vitara",
        //   "Vitara",
        //   "Baleno - GLX",
        //   "Baleno - GL",
        //   "APV Truck",
        //   "APV PANEL VAN",
        //   "Ignis",
        //   "Grand Vitara",
        //   "Grand Vitara 3 doors",
        //   "Baleno",
        //   "Swift",
        //   "Swift Dzire",
        //   "SX4",
        //   "Swift Dzire",
        //   "Ignis",
        //   "Swift",
        //   "Jimny",
        //   "Ciaz",
        //   "Ertiga",
        //   "DZIRE",
        //   "CARRY",
        //   "EECO",
        //   "FRONX",
        // ],
        // "Tata": [
        //   "Xenon",
        // ],
        // "Toyota": [
        //   "Avalon",
        //   "Hiace",
        //   "86",
        //   "Yaris",
        //   "Camry",
        //   "Aurion",
        //   "Land Cruiser Prado",
        //   "Zelas",
        //   "Hilux",
        //   "Sequoia",
        //   "Land Cruiser",
        //   "Previa",
        //   "FJ Cruiser",
        //   "Avanza",
        //   "NX200t",
        //   "RAV4",
        //   "Corolla",
        //   "PRIUS",
        //   "Fortuner",
        //   "Innova",
        //   "PRIUS",
        //   "Rush",
        //   "AVALON",
        //   "Land Cruiser Prado",
        //   "Hilux",
        //   "Fortuner",
        //   "Innova",
        //   "FJ Cruiser",
        //   "Avanza",
        //   "CAMRY",
        //   "LAND CRUISER",
        //   "RAV4",
        //   "HIACE",
        //   "COROLLA",
        //   "Supra",
        //   "GRANVIA",
        //   "YARIS",
        //   "C-HR",
        //   "HIGHLANDER",
        //   "LANDCRUISER PRADO",
        //   "COROLLA CROSS",
        //   "RAIZE",
        //   "Liteace",
        //   "GR 86",
        //   "VELOZ",
        //   "URBAN CRUISER",
        //   "CROWN",
        // ],
        // "Victory Auto": [
        //   "K1",
        //   "K2",
        //   "V1",
        //   "V2",
        // ],
        // "Volkswagen": [
        //   "Scirocco Coupe 2.0 L",
        //   "Tiguan",
        //   "Golf GTI 2.0L- 2Doors",
        //   "Golf GTI 2.0L M/T- 4 Doors",
        //   "Golf GTI 2.0L A/T- 4 Doors",
        //   "Golf GTI 2.0L- 2Doors",
        //   "Golf R 2.0 L",
        //   "Touareg SE 3.6L",
        //   "Touareg R-Line 3.6L",
        //   "Golf GTI 2.0 L",
        //   "Touareg Sport 3.6L",
        //   "Jetta S 2.0 L",
        //   "Jetta SE 2.0L",
        //   "CC SE 1.8 L",
        //   "CC S 1.8 L",
        //   "Jetta SEL 2.5L",
        //   "Passat S 2.5 L",
        //   "Passat SE 2.5L",
        //   "Passat R-Line 2.5 L",
        //   "Passat SEL 2.5L",
        //   "CC SEL 2.0 L",
        //   "CC R 3.6L",
        //   "Passat Sport 2.5 L",
        //   "Volkwagen Beetle Exclusive",
        //   "Volkwagen Beetle S",
        //   "Volkwagen Beetle SE",
        //   "Volkwagen Beetle SEL",
        //   "Tiguan S",
        //   "Tiguan SE",
        //   "Tiguan SE",
        //   "Tiguan SEL",
        //   "Tiguan R-Line",
        //   "Golf GTI 2.0L 2 Doors",
        //   "Golf R 2.0L-4 Doors",
        //   "Golf R 2.0L-2 Doors",
        //   "Golf GTI 2.0L- 4 Doors",
        //   "Golf R",
        //   "Golf SE",
        //   "Golf GTI",
        //   "Golf SEL",
        //   "Beetle SEL",
        //   "Beetle SE",
        //   "Beetle Exclusive",
        //   "Beetle S",
        //   "Jetta S",
        //   "Jetta SEL",
        //   "Jetta SE",
        //   "Tiguan SEL",
        //   "Tiguan Sport",
        //   "Passat Sport",
        //   "Passat SE",
        //   "Passat R-Line",
        //   "Passat S",
        //   "Passat SEL",
        //   "Passat SEL 2.5L-Sedan-2WD",
        //   "Touareg Sport",
        //   "Touareg R-Line",
        //   "Touareg S",
        //   "Touareg SEL",
        //   "Touareg SE",
        //   "Arteon Elegance",
        //   "Arteon R-Line 2.0L 4WD",
        //   "Arteon Elegance",
        //   "Arteon S",
        //   "Touareg Comfortline",
        //   "Touareg Trendline",
        //   "Touareg Highline",
        //   "Teramont SE",
        //   "Teramont SEL",
        //   "Touareg Trendline",
        //   "Tiguan S",
        //   "Tiguan Sport",
        //   "Golf R",
        //   "Golf GTI",
        //   "Arteon R-Line",
        //   "Arteon S",
        //   "Touareg",
        //   "Teramont S",
        //   "Touareg Trendline",
        //   "Passat Trendline",
        //   "Passat Highline",
        //   "Passat Comfortline",
        //   "Touareg Comfortline",
        //   "T-Roc Trend",
        //   "T-Roc Style",
        //   "T-Roc Sport",
        //   "Touareg R-Line",
        //   "Touareg Atmosphere",
        //   "Touareg Trend",
        //   "Teramont Trendline",
        //   "Teramont Highline",
        //   "Teramont Comfortline",
        //   "Tiguan R-Line",
        //   "Tiguan Life",
        //   "Tiguan Trend",
        //   "Tiguan Elegance",
        //   "Teramont Trendline",
        //   "T-Roc Trend",
        //   "T-Roc Sport",
        //   "T Roc Rline",
        //   "TRoc Style",
        //   "T Roc Life",
        //   "Touareg R Line",
        //   "TRoc Life",
        //   "Tiguan RLine",
        //   "Amarok Aventura",
        //   "Amarok Style",
        //   "Amarok PanAmericana",
        //   "Amarok Life",
        //   "T-Roc R-line",
        // ],
        // "Volvo": [
        //   "V40 T5 VEA",
        //   "XC90 T6 7seat",
        //   "S60 T4 VEA",
        //   "S60 T3 VEA",
        //   "XC60 T5 VEA AWD",
        //   "XC60 T5 VEA",
        //   "S90 T5",
        //   "XC90 T5 5seat",
        //   "S90 T6",
        //   "XC90 T5 7seat",
        //   "XC90 T6 7seat",
        //   "V40 T5 VEA",
        //   "XC60 T6",
        //   "XC60 T5",
        //   "XC90 T5 7seat",
        //   "S90 T5",
        //   "S90 T4",
        //   "XC40 T5",
        //   "V90CC",
        //   "XC60 T5",
        //   "XC90 T5",
        //   "XC90 T6",
        //   "V40 T3 VEA",
        //   "V40CC T5",
        //   "V40CC T4",
        //   "XC40 T4",
        //   "V90CC T6",
        //   "S90 T8",
        //   "S60 T8",
        //   "S60 T5",
        //   "XC90 T8",
        //   "S60 T4",
        //   "XC40 T3",
        //   "V60 T4",
        // ],
        // "Zhengzhou Nissan": [
        //   "RICH",
        //   "ZNA Rich",
        // ],
        "Zotye": [
          "T600",
          "T700",
          "T300",
          "SR9",
          "T700",
        ],
        "ZX": ["Terralord"],
        "ZXAUTO": ["TERRALORD"]
      };

      mapOfCarMakeAndModel.forEach((make, models) {
        var uniqueModels = models.toSet().toList();
        carDataset[make] = uniqueModels;
      });
    }

    return carDataset;
  }
}
